title: SSF Blog

description: >-
  The SSF blog is the place to go for all sorts of SEBS Scholarship Foundation news! Here you can find scholarship
  updates, volunteering news, announcements, and other fun information we'd like to share!

url: "https://blog.sebsscholarship.org"

baseurl: ""

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
  -
    scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "examples"
    values:
      sitemap: false

theme: null

exclude:
  - vendor/