title: SSF Blog

description: >-
  The SSF blog is the place to go for all sorts of SEBS Scholarship Foundation news! Here you can find scholarship
  updates, volunteering news, announcements, and other fun information we'd like to share!

url: "https://blog.sebsscholarship.org"

baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
  -
    scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "examples"
    values:
      sitemap: false
  -
    scope:
      path: "admin"
    values:
      sitemap: false

remote_theme: sebs-scholarship/Theme@2022-01-28-1

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts

algolia:
  application_id: 0XMIKXGUS3
  index_name: blog.sebsscholarship.org
  search_only_api_key: d300e661126b8f0edd61bfee928c7730
  settings:
    attributesToSnippet:
      - content:50