---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: /bin/bash -c "apk add --no-cache imagemagick wget
    && wget 'https://fonts.google.com/download?family=Montserrat' -O font.zip && unzip
    font.zip -d /usr/share/fonts/googlefonts/ && rm font.zip && chmod 755 /srv/jekyll"
  preview_docker_image: jekyll/builder:4.2.2
  mount_path: "/srv/jekyll"
  instant_preview_command: /bin/bash -c "export JEKYLL_UID=1001 && export JEKYLL_GID=1001
    && bundle install && bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site"
