name: Deploy to Test Site

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future && \
        echo \"User-agent: * Disallow: /\" > ${{ github.workspace }}/_site/robots.txt"

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Built Site
        path: ${{ github.workspace }}/_site/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - run: ssh-keyscan test.blog.sebsscholarship.org > ~/.ssh/known_hosts

    - uses: actions/download-artifact@v1.0.0
      with:
        name: Built Site

    - name: Deploy to Test Site (SSH)
      run: |
        scp -r * ${{ secrets.USERNAME }}@test.blog.sebsscholarship.org:~/staging/
        ssh ${{ secrets.USERNAME }}@test.blog.sebsscholarship.org 'rm -rf ~/test.blog.sebsscholarship.org/* && mv ~/staging/* ~/test.blog.sebsscholarship.org/'
