name: Lint and Build Production

on:
  push:
    branches:
      - 'main'

jobs:
  lint-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: true
          VALIDATE_XML: true
          VALIDATE_BASH: true
          VALIDATE_PHP: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_CSS: true

      - name: Index production site
        run: |
          docker run -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site jekyll/builder:4.1.0 \
          /bin/bash -c "chmod 777 /srv/jekyll \
          && ALGOLIA_API_KEY='${{ secrets.ALGOLIA_KEY }}' jekyll algolia --future"

      - name: Notify on success
        if: ${{ success() }}
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#800000"
          username: "SSF Blog Status Bot"
          message: >
            Updates were successfully pushed to blog:
            https://blog.sebsscholarship.org


      - name: Notify on failure
        if: ${{ failure() && steps.lint.outcome != 'failure' }}
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#800000"
          username: "SSF Blog Status Bot"
          message: >
            Aborting deployment due to unexpected error:
            https://github.com/sebs-scholarship/Blog/actions/runs/${{ github.run_id }}