name: Build and Deploy Staging

on:
  push:
    branches:
      - 'staging'

jobs:
  lint:
    name: Lint for errors
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: true
          VALIDATE_XML: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_PHP: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_CSS: true

  build:
    name: Build the site
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Staging site configuration
        run: |
          echo 'User-agent: * Disallow: /' > ${{ github.workspace }}/robots.txt
          sed -i 's_https://blog.sebsscholarship.org_https://test.blog.sebsscholarship.org_g' ${{ github.workspace }}/_config.yml

      - name: Build staging site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:4 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --drafts"

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Built Site
          path: ${{ github.workspace }}/_site/

  deploy_staging:
    name: Deploy to staging server
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Built Site
          path: Built Site

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust SSH key
        run: ssh-keyscan sebsscholarship.org > ~/.ssh/known_hosts

      - name: Deploy
        run: |
          scp -r Built\ Site/* ${{ secrets.USERNAME }}@sebsscholarship.org:~/staging/
          ssh ${{ secrets.USERNAME }}@sebsscholarship.org 'rm -rf ~/test.blog.sebsscholarship.org/* \
          && mv ~/staging/* ~/test.blog.sebsscholarship.org/'