name: Deploy to Test Site

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        chmod 777 ${{ github.workspace }}
        echo 'User-agent: * Disallow: /' > ${{ github.workspace }}/robots.txt
        sed -i 's_https://blog.sebsscholarship.org_https://test.blog.sebsscholarship.org_g' ${{ github.workspace }}/_config.yml

    - name: Build the site
      run: |
        sudo apt-get install ruby-full build-essential zlib1g-dev
        echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
        echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        gem install jekyll bundler
        pushd ${{ github.workspace }}
        jekyll build --future --drafts
        popd

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Built Site
        path: ${{ github.workspace }}/_site/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - run: ssh-keyscan test.blog.sebsscholarship.org > ~/.ssh/known_hosts

    - uses: actions/download-artifact@v1.0.0
      with:
        name: Built Site

    - name: Deploy to Test Site (SSH)
      run: |
        scp -r Built\ Site/* ${{ secrets.USERNAME }}@test.blog.sebsscholarship.org:~/staging/
        ssh ${{ secrets.USERNAME }}@test.blog.sebsscholarship.org 'rm -rf ~/test.blog.sebsscholarship.org/* && mv ~/staging/* ~/test.blog.sebsscholarship.org/'
