name: Deploy to Test Site

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        chmod 777 ${{ github.workspace }}
        echo 'User-agent: * Disallow: /' > ${{ github.workspace }}/robots.txt
        sed -i 's_https://blog.sebsscholarship.org_https://test.blog.sebsscholarship.org_g' ${{ github.workspace }}/_config.yml

    - name: Build the site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:3.8 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --drafts"

    - name: Upload artifact
      uses: actions/upload-artifact@v2.0.1
      with:
        name: Built Site
        path: ${{ github.workspace }}/_site/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - run: ssh-keyscan test.blog.sebsscholarship.org > ~/.ssh/known_hosts

    - uses: actions/download-artifact@v1.0.0
      with:
        name: Built Site

    - name: Deploy to Test Site (SSH)
      run: |
        scp -r Built\ Site/* ${{ secrets.USERNAME }}@test.blog.sebsscholarship.org:~/staging/
        ssh ${{ secrets.USERNAME }}@test.blog.sebsscholarship.org 'rm -rf ~/test.blog.sebsscholarship.org/* && mv ~/staging/* ~/test.blog.sebsscholarship.org/'
